name: Proxy Trigger

on:
  workflow_dispatch:
    inputs:
      client_data:
        description: "Client data from HTML form"
        required: true

jobs:
  trigger-main-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Main Workflow
      run: |
        echo "Triggering Submit Client Data workflow..."
        client_data=$(echo '${{ github.event.inputs.client_data }}' | jq -R .)
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{
                \"ref\": \"main\",
                \"inputs\": {
                    \"client_data\": $client_data
                }
              }" \
          https://api.github.com/repos/Radilovk/client-data-system/actions/workflows/submit-client-data.yml/dispatches
