name: Submit Client Data

on:
  repository_dispatch:
    types:
      - create_client_record

jobs:
  submit_client_data:
    runs-on: ubuntu-latest

    steps:
    - name: Generate GitHub App Token
      id: generate-token
      run: |
        APP_ID=YOUR_APP_ID
        PRIVATE_KEY=${{ secrets.GITHUB_APP_PRIVATE_KEY }}
        JWT=$(echo -n $PRIVATE_KEY | base64 --decode | openssl rsautl -sign -inkey /dev/stdin | openssl base64)
        TOKEN=$(curl -X POST \
          -H "Authorization: Bearer $JWT" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/app/installations/INSTALLATION_ID/access_tokens | jq -r '.token')
        echo "token=$TOKEN" >> $GITHUB_ENV

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Save client data
      env:
        TOKEN: ${{ env.token }}
      run: |
        TIMESTAMP=$(date +%s)
        CLIENT_FILE="clients/client_${TIMESTAMP}.json"
        echo '${{ toJson(github.event.client_data) }}' > $CLIENT_FILE
        git config user.name "GitHub App"
        git config user.email "github-app@users.noreply.github.com"
        git add $CLIENT_FILE
        git commit -m "Add client data"
        git push
