name: Submit Client Data

on:
  repository_dispatch:
    types:
      - create_client_record

permissions:
  contents: write  # Разрешаване на четене и запис на съдържание

jobs:
  submit_client_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Parse client data
      id: parse-data
      run: |
        echo '${{ toJson(github.event.client_data) }}' > client_data.json

    - name: Add client record
      run: |
        TIMESTAMP=$(date +%s)
        CLIENT_FILE="clients/client_${TIMESTAMP}.json"
        mv client_data.json $CLIENT_FILE
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add $CLIENT_FILE
        git commit -m "Add new client record"
        git push
