name: Submit Client Data

on:
  workflow_dispatch:
    inputs:
      client_data:
        description: "Client data in JSON format"
        required: true

jobs:
  process-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create client file
        run: |
          echo '${{ inputs.client_data }}' > clients/client_$(date +%s).json

      - name: Commit and Push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add clients/client_*.json
          git commit -m "Add new client response"
          git push
