name: Submit Client Data

on:
  workflow_dispatch:
    inputs:
      client_data:
        description: "Client data as JSON"
        required: true

jobs:
  process-client-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate Input
      run: |
        if ! echo "${{ github.event.inputs.client_data }}" | jq empty; then
          echo "Error: Invalid JSON provided in client_data."
          exit 1
        fi

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Create Client Data File
      run: |
        timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        mkdir -p clients
        echo "${{ github.event.inputs.client_data }}" > clients/client_${timestamp}.json

    - name: Commit and Push Client Data
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Add new client data"
        branch: main
