name: Test Secret Token

on:
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest

    steps:
    - name: Test Personal Token
      env:
        PERSONAL_TOKEN: ${{ secrets.T01 }}
      run: |
        echo "Testing Personal Token"
        curl -X GET \
          -H "Authorization: Bearer $PERSONAL_TOKEN" \
          -H "Content-Type: application/json" \
          https://api.github.com/user
