name: Submit Client Data

on:
  workflow_dispatch:
    inputs:
      client_data:
        description: 'Client Data'
        required: true
        default: '{}'

jobs:
  handle-client-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Decode client data
      run: echo '${{ github.event.inputs.client_data }}' | base64 --decode > clients/client_data.json

    - name: Save client data
      run: |
        mkdir -p clients
        echo '${{ github.event.inputs.client_data }}' | base64 --decode > clients/client_data.json
