name: Submit Client Data

on:
  repository_dispatch:
    types:
      - create_client_record

permissions:
  contents: write  # Позволява писане на файлове в хранилището

jobs:
  submit_client_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Parse client data
      run: |
        echo '${{ toJson(github.event.client_data) }}' > clients/client_$(date +%s).json

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add clients/
        git commit -m "Add new client record"
        git push
