name: Submit Client Data

on:
  workflow_dispatch:
    inputs:
      client_data:
        description: "Client data as JSON"
        required: true

jobs:
  process-client-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate Input
      run: |
        if [[ -z "${{ github.event.inputs.client_data }}" ]]; then
          echo "Error: No client data provided."
          exit 1
        fi

    - name: Create client data file
      run: |
        # Извличане на подадените данни
        echo "${{ github.event.inputs.client_data }}" > client_data.json

        # Създаване на нов JSON файл в директорията clients/
        timestamp=$(date +%s)
        mkdir -p clients
        echo "${{ github.event.inputs.client_data }}" > clients/client_${timestamp}.json

    - name: Commit and Push Client Data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add clients/
        git commit -m "Add new client data"
        git push
