name: Submit Client Data

permissions:
  contents: write         # Позволява създаване, актуализиране и изтриване на файлове
  issues: write           # Позволява създаване и управление на issues
  pull-requests: write    # Позволява управление на pull requests
  actions: write          # Позволява управление на workflows
  deployments: write      # Позволява управление на деплойменти
  packages: write         # Позволява управление на пакети
  statuses: write         # Позволява управление на статуси на commit-и

on:
  workflow_dispatch:
    inputs:
      client_data:
        description: "Client data as JSON"
        required: true

jobs:
  process-client-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate and Log Input Data
      run: |
        echo "Received data:"
        echo "${{ github.event.inputs.client_data }}"

    - name: Create client data file
      run: |
        mkdir -p clients
        timestamp=$(date +%s)
        echo "${{ github.event.inputs.client_data }}" > clients/client_${timestamp}.json

    - name: Commit and Push Client Data
      env:
        PERSONAL_TOKEN: ${{ secrets.T01 }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add clients/
        git commit -m "Add new client data at $(date)"
        git push https://x-access-token:${{ env.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git
