name: Test GitHub Token

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test GitHub Token
        run: |
          echo "Testing GitHub Token..."
          response=$(curl -s -H "Authorization: token ${{ secrets.T01 }}" https://api.github.com/user)
          echo "Response: $response"
          echo $response | jq .
