name: Test GitHub Token

on:
  workflow_dispatch:

jobs:
  test-github-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test GitHub Token
      env:
        GITHUB_TOKEN: ${{ secrets.T01 }}
      run: |
        echo "Testing GitHub Token..."
        # Изпращане на заявка към GitHub API за проверка на токена
        response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/user)
        echo "Response: $response"

        # Проверка дали токенът е валиден
        if echo "$response" | grep -q '"login"'; then
          echo "Token is valid."
        else
          echo "Invalid token or insufficient permissions."
          exit 1
        fi
