name: Test List Workflows

on:
  workflow_dispatch:

jobs:
  test-list-workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Test List Workflows
      env:
        PERSONAL_TOKEN: ${{ secrets.T01 }}
      run: |
        echo "Fetching workflows..."
        curl -X GET \
          -H "Authorization: Bearer $PERSONAL_TOKEN" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/Radilovk/client-data-system/actions/workflows
