name: Test GitHub Token Actions

on:
  workflow_dispatch:

jobs:
  test-github-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test Token - Create File
      run: |
        echo "Testing file creation..."
        echo "VGhpcyBpcyBhIHRlc3QgZmlsZSBjb250ZW50" > base64content.txt
        curl -X PUT \
          -H "Authorization: token ${{ secrets.T01 }}" \
          -H "Content-Type: application/json" \
          -d "$(cat <<EOF
{
  "message": "Create test file",
  "content": "$(cat base64content.txt)",
  "branch": "main"
}
EOF
)" \
          https://api.github.com/repos/Radilovk/client-data-system/contents/test_file.txt

    - name: Test Token - Modify File
      run: |
        echo "Testing file modification..."
        curl -X PUT \
          -H "Authorization: token ${{ secrets.T01 }}" \
          -H "Content-Type: application/json" \
          -d "$(cat <<EOF
{
  "message": "Modify test file",
  "content": "$(echo 'Updated content' | base64)",
  "sha": "$(curl -s -H 'Authorization: token ${{ secrets.T01 }}' https://api.github.com/repos/Radilovk/client-data-system/contents/test_file.txt | jq -r '.sha')",
  "branch": "main"
}
EOF
)" \
          https://api.github.com/repos/Radilovk/client-data-system/contents/test_file.txt

    - name: Test Token - Delete File
      run: |
        echo "Testing file deletion..."
        curl -X DELETE \
          -H "Authorization: token ${{ secrets.T01 }}" \
          -H "Content-Type: application/json" \
          -d "$(cat <<EOF
{
  "message": "Delete test file",
  "sha": "$(curl -s -H 'Authorization: token ${{ secrets.T01 }}' https://api.github.com/repos/Radilovk/client-data-system/contents/test_file.txt | jq -r '.sha')",
  "branch": "main"
}
EOF
)" \
          https://api.github.com/repos/Radilovk/client-data-system/contents/test_file.txt
