name: Test GitHub Token Permissions

on:
  workflow_dispatch:

jobs:
  test-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test Create File
      env:
        GITHUB_TOKEN: ${{ secrets.T01 }}
      run: |
        echo "Testing file creation..."
        echo "This is a test file." > test-file.txt
        encoded_content=$(cat test-file.txt | base64 -w 0)
        curl -X PUT \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d @- <<EOF
{
  "message": "Test file creation",
  "content": "$encoded_content",
  "branch": "main",
  "path": "test/test-file.txt"
}
EOF

    - name: Test Update File
      env:
        GITHUB_TOKEN: ${{ secrets.T01 }}
      run: |
        echo "Testing file update..."
        curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/contents/test/test-file.txt > response.json
        sha=$(jq -r '.sha' response.json)
        echo "Updated content" > test-file.txt
        encoded_content=$(cat test-file.txt | base64 -w 0)
        curl -X PUT \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d @- <<EOF
{
  "message": "Test file update",
  "content": "$encoded_content",
  "sha": "$sha",
  "branch": "main",
  "path": "test/test-file.txt"
}
EOF

    - name: Test Delete File
      env:
        GITHUB_TOKEN: ${{ secrets.T01 }}
      run: |
        echo "Testing file deletion..."
        curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/contents/test/test-file.txt > response.json
        sha=$(jq -r '.sha' response.json)
        curl -X DELETE \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d @- <<EOF
{
  "message": "Test file deletion",
  "sha": "$sha",
  "branch": "main",
  "path": "test/test-file.txt"
}
EOF
