name: Test GitHub Token

on:
  workflow_dispatch: # Можете ръчно да стартирате този workflow

jobs:
  test-token:
    runs-on: ubuntu-latest

    steps:
    - name: Test GitHub Token
      env:
        GITHUB_TOKEN: ${{ secrets.T01 }}
      run: |
        echo "Testing GitHub Token..."
        response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                     https://api.github.com/user)
        echo "Response: $response"
        if echo "$response" | grep -q '"login":'; then
          echo "Token is valid."
        else
          echo "Token is invalid or missing permissions."
          exit 1
