name: Update Proxy File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch bot_proxy.json Content and SHA
      run: |
        # Изтегляне на bot_proxy.json
        response=$(curl -s -H "Authorization: token ${{ secrets.T01 }}" \
                     https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json)

        # Извличане на съдържанието и SHA
        content=$(echo "$response" | jq -r '.content // empty')
        proxy_sha=$(echo "$response" | jq -r '.sha // empty')

        # Проверка дали съдържанието е налично
        if [[ -z "$content" || -z "$proxy_sha" ]]; then
          echo "Error: Missing content or SHA in the response" >&2
          exit 1
        fi

        # Запазване на съдържанието и SHA за последващо използване
        echo "content=$content" >> $GITHUB_ENV
        echo "proxy_sha=$proxy_sha" >> $GITHUB_ENV

    - name: Update Proxy File if Necessary
      run: |
        # Четене на текущата SHA стойност директно от Base64 съдържанието
        decoded_content=$(echo "${{ env.content }}" | base64 -d || echo "{}")
        current_sha=$(echo "$decoded_content" | jq -r '.client_data_sha // empty')

        # Четене на новата SHA стойност
        new_client_data_sha="0967ef424bce6791893e9a57bb952f80fd536e93"

        # Проверка за промяна
        if [[ "$current_sha" != "$new_client_data_sha" ]]; then
          echo "Updating bot_proxy.json with new SHA: $new_client_data_sha"

          # Подмяна на client_data_sha
          updated_content=$(echo "$decoded_content" | jq --arg new_sha "$new_client_data_sha" '.client_data_sha = $new_sha')

          # Кодиране на новото съдържание в Base64
          encoded_content=$(echo "$updated_content" | base64 -w 0)

          # Генериране на JSON за PUT заявката
          echo "{
            \"message\": \"Sync bot proxy file\",
            \"content\": \"$encoded_content\",
            \"sha\": \"${{ env.proxy_sha }}\",
            \"branch\": \"main\"
          }" > payload.json

          # PUT заявка към GitHub API
          curl -X PUT \
               -H "Authorization: token ${{ secrets.T01 }}" \
               -H "Content-Type: application/json" \
               --data @payload.json \
               https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json
        else
          echo "No update needed. SHA is up to date."
        fi
