name: Update Client Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch client_data.json SHA
      id: fetch_sha
      run: |
        # Извличане на SHA от client_data.json
        response=$(curl -H "Authorization: token ${{ secrets.T01 }}" \
                         https://api.github.com/repos/Radilovk/client-data-system/contents/client_data.json)
        sha=$(echo $response | grep -Po '"sha":\s*"\K[^"]*')
        echo "sha=$sha" >> $GITHUB_ENV

    - name: Fetch bot_proxy.json SHA and Content
      id: fetch_proxy
      run: |
        # Изтегляне на съдържанието на bot_proxy.json
        response=$(curl -H "Authorization: token ${{ secrets.T01 }}" \
                         https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json)
        content=$(echo $response | grep -Po '"content":\s*"\K[^"]*' | base64 -d)
        proxy_sha=$(echo $response | grep -Po '"sha":\s*"\K[^"]*')
        # Запазване на резултатите
        echo "content=$content" >> $GITHUB_ENV
        echo "proxy_sha=$proxy_sha" >> $GITHUB_ENV

    - name: Compare and update file
      run: |
        # Актуализиране на client_data_sha, ако е необходимо
        if [[ "$(echo "$content" | grep -Po '"client_data_sha":\s*"\K[^"]*')" != "${{ env.sha }}" ]]; then
          echo "Updating bot_proxy.json with new SHA: ${{ env.sha }}"

          # Подмяна на client_data_sha
          updated_content=$(echo "$content" | sed "s/\"client_data_sha\": \".*\"/\"client_data_sha\": \"${{ env.sha }}\"/")

          # Кодиране на актуализираното съдържание в Base64
          encoded_content=$(echo "$updated_content" | base64 -w 0)

          # Генериране на JSON файл за PUT заявката
          echo "{
            \"message\": \"Sync bot proxy file\",
            \"content\": \"$encoded_content\",
            \"sha\": \"${{ env.proxy_sha }}\",
            \"branch\": \"main\"
          }" > payload.json

          # PUT заявка към GitHub API
          curl -X PUT \
               -H "Authorization: token ${{ secrets.T01 }}" \
               -H "Content-Type: application/json" \
               --data @payload.json \
               https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json
        else
          echo "No update needed. client_data_sha is up to date."
        fi
