- name: Update proxy file
  run: |
    # Четене на текущия SHA от bot_proxy.json
    current_sha=$(cat bot_proxy.json | grep '"sha"' | awk -F'"' '{print $4}')
    echo "Current SHA: $current_sha"

    # Четене на текущия client_data_sha
    new_client_data_sha="0967ef424bce6791893e9a57bb952f80fd536e93"

    # Обновяване на JSON съдържание
    new_proxy_content=$(cat bot_proxy.json | sed "s/\"client_data_sha\": \".*\"/\"client_data_sha\": \"$new_client_data_sha\"/")

    # Кодиране на новото съдържание в Base64
    encoded_proxy=$(echo "$new_proxy_content" | base64 -w 0)

    # PUT заявка за актуализиране на файла
    curl -X PUT \
         -H "Authorization: token ${{ secrets.T01 }}" \
         -H "Content-Type: application/json" \
         -d @- <<EOF
{
  "message": "Sync bot proxy file",
  "content": "$encoded_proxy",
  "sha": "$current_sha",
  "branch": "main"
}
EOF
