name: Update Proxy File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch current SHA
      id: fetch_sha
      run: |
        response=$(curl -H "Authorization: token ${{ secrets.T01 }}" https://api.github.com/repos/Radilovk/client-data-system/contents/client_data.json)
        sha=$(echo $response | grep -Po '"sha":\s*"\K[^"]*')
        echo "sha=$sha" >> $GITHUB_ENV

    - name: Update proxy file
      run: |
        # Четем текущия SHA от bot_proxy.json
        current_sha=$(cat bot_proxy.json | grep '"sha"' | awk -F'"' '{print $4}')
        
        # Актуализираме JSON съдържанието
        new_proxy_content=$(cat bot_proxy.json | sed "s/\"client_data_sha\": \".*\"/\"client_data_sha\": \"${{ env.sha }}\"/")

        # Кодиране в Base64
        encoded_proxy=$(echo "$new_proxy_content" | base64 -w 0)

        # PUT заявка
        curl -X PUT \
             -H "Authorization: token ${{ secrets.T01 }}" \
             -H "Content-Type: application/json" \
             -d @- <<EOF
{
  "message": "Sync bot proxy file",
  "content": "$encoded_proxy",
  "sha": "$current_sha",
  "branch": "main"
}
EOF
