- name: Fetch bot_proxy.json Content and SHA
  run: |
    # Изтегляне на bot_proxy.json
    response=$(curl -s -H "Authorization: token ${{ secrets.T01 }}" \
                     https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json)

    # Извличане на съдържанието и SHA чрез jq
    content=$(echo "$response" | jq -r '.content // empty')
    proxy_sha=$(echo "$response" | jq -r '.sha // empty')

    # Проверка дали съдържанието е валидно Base64
    if [[ -n "$content" ]]; then
      decoded_content=$(echo "$content" | tr -d '\n' | base64 -d 2>/dev/null || echo "INVALID_BASE64")
      if [[ "$decoded_content" == "INVALID_BASE64" ]]; then
        echo "Warning: Content is not valid Base64. Skipping decoding." >&2
        decoded_content=""
      fi
    else
      echo "Error: Content is missing in the response" >&2
      exit 1
    fi

    # Запазване на съдържанието и SHA
    echo "$decoded_content" > bot_proxy.json
    echo "proxy_sha=$proxy_sha" >> $GITHUB_ENV
