name: Update Proxy File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch client_data.json SHA
      id: fetch_sha
      run: |
        response=$(curl -s -H "Authorization: token ${{ secrets.T01 }}" https://api.github.com/repos/Radilovk/client-data-system/contents/client_data.json)
        if echo "$response" | jq -e '.sha' > /dev/null; then
          sha=$(echo $response | jq -r '.sha')
          echo "sha=$sha" >> $GITHUB_ENV
        else
          echo "Failed to fetch SHA. Response: $response"
          exit 1
        fi

    - name: Update bot_proxy.json
      run: |
        echo '{"client_data_sha": "${{ env.sha }}", "last_updated": "$(date --iso-8601=seconds)"}' > bot_proxy.json
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add bot_proxy.json
        if ! git diff-index --quiet HEAD; then
          git commit -m "Update bot_proxy.json with new SHA"
          git pull origin main --rebase
          git push origin main
        else
          echo "No changes to commit"
        fi

    - name: Update proxy file
      run: |
        new_proxy_content=$(cat bot_proxy.json | jq -c '.')
        encoded_proxy=$(echo "$new_proxy_content" | base64 -w 0)
        sha=$(curl -s -H "Authorization: token ${{ secrets.T01 }}" https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json | jq -r '.sha')

        if [ -z "$sha" ]; then
          echo "Failed to fetch SHA for bot_proxy.json. Exiting."
          exit 1
        fi

        response=$(curl -s -X PUT -H "Authorization: token ${{ secrets.T01 }}" \
          -H "Content-Type: application/json" \
          -d "{\"message\": \"Sync bot proxy file\", \"content\": \"$encoded_proxy\", \"sha\": \"$sha\", \"branch\": \"main\"}" \
          https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json)

        if echo "$response" | jq -e '.commit.sha' > /dev/null; then
          echo "Successfully updated bot_proxy.json. Response: $response"
        else
          echo "Failed to update bot_proxy.json. Response: $response"
          exit 1
        fi
