name: Update Client Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch client_data.json SHA
      id: fetch_sha
      run: |
        # Изтегляне на SHA от client_data.json
        response=$(curl -H "Authorization: token ${{ secrets.T01 }}" \
                         https://api.github.com/repos/Radilovk/client-data-system/contents/client_data.json)
        sha=$(echo $response | grep -Po '"sha":\s*"\K[^"]*')
        echo "sha=$sha" >> $GITHUB_ENV

    - name: Compare and update file
      run: |
        # Извличане на текущия client_data_sha от bot_proxy.json
        current_sha=$(cat bot_proxy.json | grep '"client_data_sha"' | awk -F'"' '{print $4}')
        echo "Current client_data_sha: $current_sha"

        # Проверка за промяна в SHA
        if [[ "$current_sha" != "${{ env.sha }}" ]]; then
          echo "Updating bot_proxy.json with new SHA: ${{ env.sha }}"

          # Създаване на ново съдържание за bot_proxy.json
          new_proxy_content=$(cat bot_proxy.json | sed "s/\"client_data_sha\": \".*\"/\"client_data_sha\": \"${{ env.sha }}\"/")
          echo "$new_proxy_content" > updated_bot_proxy.json

          # Кодиране в Base64
          encoded_proxy=$(cat updated_bot_proxy.json | base64 -w 0)

          # PUT заявка към GitHub API
          curl -X PUT \
               -H "Authorization: token ${{ secrets.T01 }}" \
               -H "Content-Type: application/json" \
               -d @- <<EOF
{
  "message": "Sync bot proxy file",
  "content": "$encoded_proxy",
  "branch": "main"
}
EOF
        else
          echo "No update needed. client_data_sha is up to date."
        fi
