name: Update Client Data

on:
  workflow_dispatch:
    inputs:
      client_id:
        description: 'Client ID'
        required: true
      client_data:
        description: 'Base64 encoded client data'
        required: true

jobs:
  upload:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Create client JSON file
      env:
        CLIENT_ID: ${{ github.event.inputs.client_id }}
        CLIENT_DATA: ${{ github.event.inputs.client_data }}
      run: |
        mkdir -p clients
        echo "$CLIENT_DATA" | base64 --decode > clients/client_${CLIENT_ID}.json

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add clients/client_${CLIENT_ID}.json
        git commit -m "Add client file for ${CLIENT_ID}"
        git push origin main

    - name: Update proxy file
      env:
        CLIENT_SHA: ${{ github.event.inputs.client_data }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Извличане на текущо съдържание на bot_proxy.json
        new_proxy_content=$(cat bot_proxy.json | jq -c '. | .client_data_sha = env.CLIENT_SHA')
        
        # Конвертиране на JSON в base64 формат
        encoded_proxy=$(echo "$new_proxy_content" | base64 -w 0)

        # Ъпдейт на bot_proxy.json чрез API
        curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
             -H "Content-Type: application/json" \
             -d "{\"message\": \"Sync bot proxy file\", \"content\": \"$encoded_proxy\", \"sha\": \"$(jq -r .sha bot_proxy.json)\", \"branch\": \"main\"}" \
             https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json
