name: Upload Client Data

on:
  repository_dispatch:
    types: [create-client-file]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Decode and create client JSON
      env:
        CLIENT_ID: ${{ github.event.client_id }}
        CLIENT_DATA: ${{ github.event.client_data }}
      run: |
        mkdir -p clients
        echo "$CLIENT_DATA" | base64 --decode > clients/client_${CLIENT_ID}.json

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add clients/client_${CLIENT_ID}.json
        git commit -m "Add client file for ${CLIENT_ID}"
        git push origin main

    - name: Update bot_proxy.json
      env:
        CLIENT_ID: ${{ github.event.client_id }}
        BOT_PROXY: bot_proxy.json
      run: |
        NEW_SHA=$(git hash-object clients/client_${CLIENT_ID}.json)
        jq --arg sha "$NEW_SHA" \
           --arg date "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
           '.client_data_sha = $sha | .last_updated = $date' \
           $BOT_PROXY > bot_proxy_updated.json

        mv bot_proxy_updated.json $BOT_PROXY

        git add $BOT_PROXY
        git commit -m "Update bot_proxy.json with new SHA for ${CLIENT_ID}"
        git push origin main
