name: Upload Client Data

on:
  workflow_dispatch:
    inputs:
      client_id:
        description: "Client ID"
        required: true
      client_data:
        description: "Base64 encoded client data"
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install jq for JSON handling
    - name: Install jq
      run: sudo apt-get install -y jq

    # Create client JSON file
    - name: Create client JSON file
      env:
        CLIENT_ID: ${{ github.event.inputs.client_id }}
        CLIENT_DATA: ${{ github.event.inputs.client_data }}
      run: |
        mkdir -p clients
        echo "$CLIENT_DATA" | base64 --decode > clients/client_${CLIENT_ID}.json
        
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add clients/client_${CLIENT_ID}.json
        git commit -m "Add client file for ${CLIENT_ID}"
        git push origin main

    # Update bot_proxy.json file
    - name: Update bot_proxy.json
      env:
        CLIENT_ID: ${{ github.event.inputs.client_id }}
        BOT_PROXY: bot_proxy.json
      run: |
        # Generate SHA for the newly created client file
        NEW_SHA=$(git hash-object clients/client_${CLIENT_ID}.json)
        
        # Update bot_proxy.json with new SHA and timestamp
        jq --arg sha "$NEW_SHA" \
           --arg date "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
           '.client_data_sha = $sha | .last_updated = $date' \
           $BOT_PROXY > bot_proxy_updated.json
        
        mv bot_proxy_updated.json $BOT_PROXY
        
        git add $BOT_PROXY
        git commit -m "Update bot_proxy.json with new SHA for ${CLIENT_ID}"
        git push origin main
