name: Update Client Data

on:
  workflow_dispatch:
    inputs:
      client_id:
        description: 'Client ID'
        required: true
      client_data:
        description: 'Base64 encoded client data'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Update proxy file
      env:
        CLIENT_ID: ${{ github.event.inputs.client_id }}
        CLIENT_DATA: ${{ github.event.inputs.client_data }}
        GITHUB_TOKEN: ${{ secrets.T01 }}
      run: |
        # Decode the Base64 encoded client data and save to a new JSON file
        echo "$CLIENT_DATA" | base64 --decode > clients/client_${CLIENT_ID}.json

        # Generate a new SHA for the client file
        NEW_SHA=$(git hash-object clients/client_${CLIENT_ID}.json)

        # Update bot_proxy.json with the new SHA and timestamp
        jq --arg sha "$NEW_SHA" \
           --arg date "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
           '.client_data_sha = $sha | .last_updated = $date' \
           bot_proxy.json > bot_proxy_temp.json

        mv bot_proxy_temp.json bot_proxy.json

        # Commit changes
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add clients/client_${CLIENT_ID}.json bot_proxy.json
        git commit -m "Update client file and bot proxy for ${CLIENT_ID}"
        git push origin main
