name: Upload Client Data

on:
  repository_dispatch:
    types: [create-client-file]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Decode and create client JSON
      env:
        CLIENT_ID: ${{ github.event.client_id }}
        CLIENT_DATA: ${{ github.event.client_data }}
      run: |
        mkdir -p clients
        echo "$CLIENT_DATA" | base64 --decode > clients/client_${CLIENT_ID}.json

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add clients/client_${CLIENT_ID}.json
        git commit -m "Add client file for ${CLIENT_ID}"
        git push origin main

    - name: Update bot_proxy.json
      env:
        CLIENT_ID: ${{ github.event.client_id }}
        BOT_PROXY: bot_proxy.json
        TOKEN: ${{ secrets.T01 }}
      run: |
        NEW_SHA=$(git hash-object clients/client_${CLIENT_ID}.json)
        new_proxy_content=$(cat $BOT_PROXY | jq -c '. | .client_data_sha = "'$NEW_SHA'" | .last_updated = "'$(date --iso-8601=seconds)'"')
        encoded_proxy=$(echo "$new_proxy_content" | base64)

        curl -X PUT \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                "message": "Sync bot proxy file",
                "content": "'"$encoded_proxy"'",
                "sha": "'"$(cat $BOT_PROXY | jq -r '.sha')"'",
                "branch": "main"
            }' \
            https://api.github.com/repos/Radilovk/client-data-system/contents/$BOT_PROXY
