name: Update Client Data

on:
  workflow_dispatch:
    inputs:
      client_id:
        description: 'Client ID'
        required: true
      client_data:
        description: 'Base64 encoded client data'
        required: true

jobs:
  upload:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Create client JSON file
      env:
        CLIENT_ID: ${{ github.event.inputs.client_id }}
        CLIENT_DATA: ${{ github.event.inputs.client_data }}
      run: |
        mkdir -p clients
        echo "$CLIENT_DATA" | base64 --decode > clients/client_${CLIENT_ID}.json

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add clients/client_${CLIENT_ID}.json
        git commit -m "Add client file for ${CLIENT_ID}"
        git push origin main

    - name: Update bot_proxy.json
      env:
        CLIENT_SHA: ${{ github.event.inputs.client_data }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Генериране на ново съдържание за bot_proxy.json
        new_proxy_content=$(jq -n \
          --arg sha "$CLIENT_SHA" \
          --arg date "$(date --iso-8601=seconds)" \
          '{"client_data_sha": $sha, "last_updated": $date}')

        # Кодираме съдържанието в base64
        encoded_proxy=$(echo "$new_proxy_content" | base64 --wrap=0)

        # Взимаме текущото SHA на файла
        current_sha=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json | jq -r '.sha')

        # Изпращаме заявка за обновяване на файла
        curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$(jq -n \
            --arg message "Sync bot proxy file" \
            --arg content "$encoded_proxy" \
            --arg sha "$current_sha" \
            '{message: $message, content: $content, sha: $sha}')" \
          https://api.github.com/repos/Radilovk/client-data-system/contents/bot_proxy.json
