name: Save Client Data

on:
  repository_dispatch:
    types: [add-client]

jobs:
  save-client-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Save client data
      env:
        GITHUB_TOKEN: ${{ secrets.T01 }}
      run: |
        # Извличане на данни от събитието
        client_data=$(echo "${{ github.event.client_data }}" | base64 -d)
        echo "$client_data" > client_data.json
        
        # Създаване на директория и запис на файла
        mkdir -p clients
        timestamp=$(date +%s)
        mv client_data.json clients/client_${timestamp}.json

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add clients/
        git commit -m "Add new client data"
        git push
