name: Update Client Data

on:
  workflow_dispatch:
    inputs:
      client_id:
        description: 'Client ID'
        required: true
      client_data:
        description: 'Base64 encoded client data'
        required: true

jobs:
  upload:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Create client JSON file
      env:
        CLIENT_ID: ${{ github.event.inputs.client_id }}
        CLIENT_DATA: ${{ github.event.inputs.client_data }}
      run: |
        mkdir -p clients
        echo "$CLIENT_DATA" | base64 --decode > clients/client_${CLIENT_ID}.json

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add clients/client_${CLIENT_ID}.json
        git commit -m "Add client file for ${CLIENT_ID}"
        git push origin main

    - name: Update bot_proxy.json
      env:
        CLIENT_ID: ${{ github.event.inputs.client_id }}
        CLIENT_SHA: ${{ github.event.inputs.client_data }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Генериране на ново съдържание за bot_proxy.json
        jq -n --arg sha "$CLIENT_SHA" --arg date "$(date --iso-8601=seconds)" \
          '{"client_data_sha": $sha, "last_updated": $date}' > bot_proxy.json

        # Добавяне и commit на файла само ако има промени
        if ! git diff --quiet bot_proxy.json; then
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add bot_proxy.json
          git commit -m "Update bot_proxy.json with new SHA"
          git push origin main
        else
          echo "No changes to commit in bot_proxy.json"
        fi
